name: student_timetable_app
description: Student timetable app with Google domain login.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_sign_in: ^6.2.1
  http: ^1.2.2
  shared_preferences: ^2.3.2
  flutter_local_notifications: ^18.0.1
  timezone: ^0.10.0
  path_provider: ^2.1.5


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
